// src/constants/notification.types.js
export const NOTIFICATION_TYPES = {
  // Marketplace & Order
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',

  // Product & Inventory
  PRODUCT_APPROVED: 'PRODUCT_APPROVED',
  PRODUCT_REJECTED: 'PRODUCT_REJECTED',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',

  // Report & Moderation
  REPORT_RECEIVED: 'REPORT_RECEIVED',
  REPORT_RESOLVED: 'REPORT_RESOLVED',
  WARNING: 'WARNING',

  // Social & Communication
  LIKE: 'LIKE',
  COMMENT: 'COMMENT',

  // System Notifications
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  PROMOTION: 'PROMOTION',
  GENERAL: 'GENERAL'
};